config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "subs#index"

  resources :users
  resource :session, only:[:new,:create,:destroy]

  resources :subs 
  resources :posts,only: [:new, :create,:destroy,:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  author_id  :integer
#

class Post < ApplicationRecord
  validates  :title, presence:true
 
  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User

  has_many :subpostjoins,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :Subpostjoin,
    inverse_of: :post

  has_many :subs,
    through: :subpostjoins,
    source: :sub

end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  moderator_id :integer          not null
#  title        :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  description  :text
#

class Sub < ApplicationRecord
  validates :moderator_id, :title,presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :subpostjoins,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :Subpostjoin,
    inverse_of: :sub

  has_many :posts,
    through: :subpostjoins,
    source:  :post

end

app/models/subpostjoin.rb
# == Schema Information
#
# Table name: subpostjoins
#
#  id         :integer          not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Subpostjoin < ApplicationRecord

  belongs_to :post,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :Post

  belongs_to :sub,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :Sub

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#


class User < ApplicationRecord
  attr_reader :password
  after_initialize :ensure_session_token

  validates :password, allow_nil:true, length:{minimum: 6}
  validates :session_token, :username, presence:true, uniqueness: true
  validates :password_digest, presence: true
   #has_many :posts
   #has_many :subs
   #join table

  def password=(pass)
    @password = pass
    self.password_digest = BCrypt::Password.create(pass)
  end

  def ensure_session_token
    self.session_token ||= gen_session_token
  end
  def reset_session_token!
    self.session_token ||= gen_session_token
  end
 
  def gen_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def is_password?(pass)
    BCrypt::Password.new(self.password_digest).is_password?(pass)
  end
  
  def self.find_by_credentials(uname,pass)
    @user = User.find_by(username: uname)
    return nil if @user.nil?
    if @user.is_password?(pass)
      return @user
    end
    return nil
  end

  def self.find_by_session_token(st)
    User.find_by(session_token: st)
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :is_logged?



  def current_user
    User.find_by_session_token(session[:session_token])
  end
  
  def login!(user)
    user.reset_session_token!
    user.save
    session[:session_token] = user.session_token
  end
  
  def logout!
    @current_user = current_user
    @current_user.reset_session_token!
    @current_user.save!
    session[:session_token] = nil
  end
  
  def is_logged?
   !!current_user
  end
  
  def require_logged_in!
    redirect_to new_session_url unless is_logged?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :require_logged_in!, only:[:new,:create]
  def show
    @post = Post.find(params[:id])
  end

  def new
    @subs = Sub.all  
  end

  def create
    sub_ids = params[:sub][:id].map{|el|el.to_i }
   cu_id =  current_user.id

    @post = Post.new(title: post_params[:title], 
                    url: post_params[:url],
                    content: post_params[:content],
                    sub_ids: sub_ids,
                    author_id: cu_id)
    if @post.save
       redirect_to subs_url
    else
      flash[:errors]= @post.errors.full_messages
    end
  end

  private
  def post_params
    params.require(:post).permit(:title,:url,:content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new

  end

  def create
    @user = User.find_by_credentials(params[:user][:username],params[:user][:password])
    if @user
      login!(@user)
      render :new
    else
      flash[:errors] =["Invalid Credentials"]
      render :new
    end
  end
  
  def destroy
    logout!
    render :new
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in!, only: [:new, :create]

  def index
    @subs = Sub.all
  end
  
  def show
    @sub = Sub.find(params[:id])
  end

  def new   
  end

  def create
   @sub = Sub.new(sub_params) 
   @sub.moderator_id = current_user.id
   if @sub.save
     redirect_to subs_url
   else
     flash[:errors] = @sub.errors.full_messages
     render :new
   end
  end

  private 
  def sub_params
    params.require(:sub).permit(:title,:description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def create
    @user = User.new(user_params)
  
    if @user.save
      login!(@user)
      redirect_to new_session_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private 
  def user_params
    params.require(:user).permit(:username, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if is_logged? %>
      <%= current_user.username %> | 
       <%= button_to "Sign Out", session_url, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_user_url %>
      <%= link_to "Sign In", new_session_url %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
<h1>New Post!</h1>

<%= render 'shared/errors' %>
<form  action="<%= posts_url%>" method="post">
  <input name="_method" value="POST" type="hidden">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <br><br>
  <label for="Title">Title</label>
  <input type="text" name="post[title]" value="">
  <br>
  <label for="URL">URL</label>
  <input type="text" name="post[url]"value="">
  <br><br>
  <label for="Content">Content</label>
  <textarea id="Content" name="post[content]">
  </textarea>

  <br>

  <label>
    <% @subs.each do |sub|%>
      <input type="checkbox" name="sub[id][]" value="<%=sub.id %>">
      <%= sub.title %><br>
    <% end %>
  </label>

  <input type="submit" value="Submit!">

</form>

app/views/posts/show.html.erb
<div id="post-show">
  <h1><%= @post.title %> by <%= @post.author.username %> <h1>
  <h3>url</h3>
  <h3><%= @post.url %></h3>
  <div id="post-content">
    <h3>content:</h3>
    <p><%= @post.content %></p>
  </div>

  <% if is_logged? %> 
  <%= link_to 'Make New Post', new_post_url() %>
  <% end %>

</div>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
   <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/subs/index.html.erb
<div id="all-subs">
  <h1>All The Subs!</h1>
  
  <ul>
  <% @subs.each do |sub| %>
   <li><%= link_to sub.title, sub_url(sub) %></li>
  <% end %>
  </ul>
</div>
<% if is_logged? %>
  <%= link_to 'New Sub', new_sub_url %>
<% end %>

app/views/subs/new.html.erb
<h1>Add a Sub</h1>

<%= render 'shared/errors' %>
<form  action="<%= subs_url %>" method="post">
  <input name="_method" value="POST" type="hidden">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

  <label for="Title">Title</label>
  <input type="text" id="Title"name="sub[title]" value="">

  <label for="Description">Description</label>
  <textarea name="sub[description]" value="">
  </textarea>
  <input type="submit" value="Add Sub">

</form>

app/views/subs/show.html.erb
<div id="sub-show">
  <h1><%= @sub.title %></h1>
  <h3>description</h3>
  <h3><%= @sub.description %></h3>



  <% if is_logged? %> 
  <%= link_to 'Make New Post', new_post_url() %>
  <% end %>
  <ul>
   <% @sub.posts.each do |post| %>
    <li>
      <%= link_to post.title, post_url(post) %>
    </li>
   <% end %>
  </ul>


</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'shared/errors' %>
<form  action="<%= users_url %>" method="post">
  <input name="_method" value="POST" type="hidden">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

  <label for="Username">Username</label>
  <input type="text" name="user[username]" value="">

  <label for="Password">Password</label>
  <input type="password" name="user[password]" value="">

  <input type="submit" value="Sign Up">

</form>